
title: Vologue's Blog
description: ""
baseurl: "" 
url: "https://blog.vologue.dev" 
twitter_username: _vologue
github_username:  vologue
email: raghav.sp98@gmail.com

include:
  - favicon.ico
show_excerpts: false
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: classic
  nav_pages:
  - my_music.md
  social_links:
    twitter: _vologue
    github: vologue
#author:
#  name: vologue
#  email: raghav.sp98@gmail.com